[project]
name = "multi-language-model-evaluation-framework"
version = "0.1.0"
description = "Evaluation framework for general dataset using Langfuse, LiteLLM and multi-metric analysis"
readme = "README.md"
requires-python = ">3.11"
dependencies = [
    "langchain",
    "langchain-core",
    "langchain-mcp-adapters",
    "langchain-litellm",
    "langfuse>=3.10.1",
    "langgraph>=0.6.6",
    "litellm>=1.80.15",
    "openpyxl",
    "pandas>=2.3.3",
    "pydantic",
    "python-dotenv",
]