# License Apache 2.0: (c) 2026 Athena-Reply
# ---------------------------------------------------------------------------
# Backward-compatibility shim.
# The canonical models now live in ``open_arena_core.models``.
# This file re-exports everything so old imports like
#   ``from src.api import models as api`` continue to work.
# ---------------------------------------------------------------------------
from open_arena_core.models import *  # noqa: F401, F403
from open_arena_core.models import (  # noqa: F401
    LeaderboardVisibility,
    RunMode,
    EnvironmentSourceKind,
    CacheStatus,
    RuntimeSecretRef,
    Source,
    RuntimeAttribute,
    ModelExecutionConfig,
    ModelExecutionConfigPatch,
    ModelDefinitionCreate,
    ModelDefinitionPatch,
    ModelDefinition,
    ModelCatalogReplace,
    ModelCatalogPatch,
    ModelCatalog,
    DatasetBinding,
    EnvironmentRuntimePolicy,
    IsolationMode,
    SandboxPolicy,
    Strategy,
    ResetPolicy,
    FieldSelector,
    Source1,
    ContextBinding,
    Direction,
    MetricDefinition,
    VerifierSuiteCreate,
    VerifierSuitePatch,
    VerifierSuite,
    VerifierSuiteRef,
    VerifierSuiteInline,
    EnvironmentSource,
    EnvironmentMembershipPatch,
    EnvironmentRef,
    RankingPolicy,
    RankingPolicyPatch,
    LeaderboardPatch,
    ReuseScope,
    ReusePolicy,
    GeneratorRunConfig,
    AgentRunConfig,
    CacheHit,
    RunStatus,
    MetricResult,
    TrajectorySummary,
    AggregateMetric,
    LeaderboardEntry,
    ModelDefinitionListResponse,
    VerifierSuiteListResponse,
    LeaderboardEntryListResponse,
    DiscoveryIdentifier,
    DiscoveryIdentifierListResponse,
    ErrorDetail,
    VerifierSuiteBinding,
    InlineEnvironmentDefinition,
    EnvironmentCreate,
    EnvironmentPatch,
    Environment,
    EnvironmentInlineMembership,
    EnvironmentMembership,
    Leaderboard,
    DirectRunPair,
    SubjectResult,
    RunResult,
    EnvironmentMembershipListResponse,
    EnvironmentListResponse,
    EnvironmentVersion,
    EnvironmentVersionListResponse,
    LeaderboardListResponse,
    Error,
    EnvironmentMembershipCreate,
    LeaderboardBootstrap,
    LeaderboardCreate,
    RunSelection1,
    RunSelection2,
    RunSelection,
    GeneratorRunCreate,
    AgentRunCreate,
    Run,
    RunListResponse,
    RunCreate,
)
