# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-27T10:02:20+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    Field,
    RootModel,
    confloat,
    conint,
)


class LeaderboardVisibility(StrEnum):
    private = 'private'
    organization = 'organization'
    public = 'public'


class RunMode(StrEnum):
    generator = 'generator'
    agent = 'agent'


class EnvironmentSourceKind(StrEnum):
    huggingface_hub = 'huggingface_hub'
    github_repo = 'github_repo'
    prime_environment_hub = 'prime_environment_hub'
    inline = 'inline'


class CacheStatus(StrEnum):
    pending = 'pending'
    miss = 'miss'
    partial_hit = 'partial_hit'
    hit = 'hit'
    bypassed = 'bypassed'


class RuntimeSecretRef(BaseModel):
    name: str
    env_var: str
    required: bool | None = True
    description: str | None = Field(
        None,
        description="Human-readable note describing the secret's purpose or expected format.",
    )


class Source(StrEnum):
    literal = 'literal'
    env_var = 'env_var'
    secret_ref = 'secret_ref'


class RuntimeAttribute(BaseModel):
    name: str
    source: Source
    value: str | None = None
    env_var: str | None = None
    secret_name: str | None = None
    required: bool | None = False


class ModelExecutionConfig(BaseModel):
    provider: str = Field(
        ...,
        description='openai, anthropic, ollama, openrouter, mlflow_gateway, litellm_proxy, deployment, etc.',
    )
    model_name: str
    model_version: str
    routing_key: str | None = None
    base_url: AnyUrl | None = None
    api_format: str | None = None
    temperature: float | None = None
    max_tokens: int | None = None
    timeout_seconds: int | None = None
    retry_policy: dict[str, Any] | None = None
    headers: dict[str, str] | None = None
    required_secrets: list[RuntimeSecretRef] | None = None
    runtime_attributes: list[RuntimeAttribute] | None = None
    hyperparameters: dict[str, Any] | None = None
    extra: dict[str, Any] | None = None


class ModelExecutionConfigPatch(BaseModel):
    provider: str | None = Field(
        None,
        description='openai, anthropic, ollama, openrouter, mlflow_gateway, litellm_proxy, deployment, etc.',
    )
    model_name: str | None = None
    model_version: str | None = None
    routing_key: str | None = None
    base_url: AnyUrl | None = None
    api_format: str | None = None
    temperature: float | None = None
    max_tokens: int | None = None
    timeout_seconds: int | None = None
    retry_policy: dict[str, Any] | None = None
    headers: dict[str, str] | None = None
    required_secrets: list[RuntimeSecretRef] | None = None
    runtime_attributes: list[RuntimeAttribute] | None = None
    hyperparameters: dict[str, Any] | None = None
    extra: dict[str, Any] | None = None


class ModelDefinitionCreate(BaseModel):
    name: str
    display_name: str | None = None
    family: str | None = None
    tags: list[str] | None = None
    runtime: ModelExecutionConfig
    metadata: dict[str, Any] | None = None


class ModelDefinitionPatch(BaseModel):
    name: str | None = None
    display_name: str | None = None
    family: str | None = None
    tags: list[str] | None = None
    runtime: ModelExecutionConfigPatch | None = None
    metadata: dict[str, Any] | None = None


class ModelDefinition(BaseModel):
    id: UUID
    name: str
    display_name: str | None = None
    family: str | None = None
    tags: list[str] | None = None
    runtime: ModelExecutionConfig
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ModelCatalogReplace(BaseModel):
    name: str | None = 'leaderboard-default'
    models: list[ModelDefinitionCreate]
    metadata: dict[str, Any] | None = None


class ModelCatalogPatch(BaseModel):
    name: str | None = None
    metadata: dict[str, Any] | None = None


class ModelCatalog(BaseModel):
    name: str
    models: list[ModelDefinition]
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DatasetBinding(BaseModel):
    provider: str = Field(
        ...,
        description='huggingface, local, folder, langfuse, langsmith, opik, phoenix, braintrust, or custom.',
    )
    source_ref: str | None = Field(
        None,
        description='Dataset identifier such as HF path, repo path, or registry key.',
    )
    version: str | None = None
    selector: dict[str, Any] | None = None
    input_template: str | None = None
    output_template: str | None = None
    preprocessing: list[dict[str, Any]] | None = None
    metadata: dict[str, Any] | None = None


class EnvironmentRuntimePolicy(BaseModel):
    supported_modes: list[RunMode] | None = Field(None, min_length=1)
    batch_size: conint(ge=1) | None = None
    max_concurrency: conint(ge=1) | None = None
    reuse_key_fields: list[str] | None = Field(
        None,
        description='Fields contributing to run reuse, such as model_version, environment_version, mode, and selected entries from `runtime.hyperparameters`.',
    )
    metadata: dict[str, Any] | None = None


class IsolationMode(StrEnum):
    none = 'none'
    container = 'container'
    vm = 'vm'
    remote = 'remote'


class SandboxPolicy(BaseModel):
    enabled: bool | None = False
    isolation_mode: IsolationMode | None = None
    image: str | None = None
    """Warm OCI image reference (e.g. ``ghcr.io/org/eval-env@sha256:...``) or
    sandbox template ref.  Used to skip cold-start image pulls."""
    per_task_sandbox: bool | None = False
    """When ``True``, a fresh sandbox is launched for every task in the
    dataset (fan-out execution — P2-2).  Stored here; acted on by the
    execution layer once P2-2 is implemented."""
    bootstrap: dict[str, Any] | None = None
    teardown: dict[str, Any] | None = None
    limits: dict[str, Any] | None = None


class Strategy(StrEnum):
    per_task = 'per_task'
    per_run = 'per_run'
    manual = 'manual'
    external = 'external'


class ResetPolicy(BaseModel):
    strategy: Strategy | None = None
    reset_endpoint: AnyUrl | None = None
    snapshot_key: str | None = None
    metadata: dict[str, Any] | None = None


class FieldSelector(BaseModel):
    in_mask: list[str] | None = None
    out_mask: list[str] | None = None
    in_mask_pattern: str | None = None
    out_mask_pattern: str | None = None
    extract: str | None = None


class Source1(StrEnum):
    input = 'input'
    reference = 'reference'
    trajectory = 'trajectory'
    output = 'output'
    environment = 'environment'


class ContextBinding(BaseModel):
    slot: str
    source: Source1
    selector: FieldSelector | None = None
    required: bool | None = True


# NOTE(#74): ``Direction`` is a plain ``Enum`` (not ``StrEnum``).  This is what
# datamodel-codegen emits for this schema, and it is required for correctness:
# downstream code (src/api/service.py ``_direction_value``) normalises the value
# with ``isinstance(direction, str)`` -> return as-is, else ``direction.value``.
# A ``StrEnum`` member passes that ``isinstance(str)`` check and leaks the enum
# object into the YAML run-config (yaml.safe_dump cannot represent it).  A plain
# ``Enum`` takes the ``.value`` branch and yields the str "max".  Do not change
# this back to ``StrEnum`` on regen.
class Direction(Enum):
    max = 'max'
    min = 'min'


class MetricDefinition(BaseModel):
    name: str
    metric_kind: str = Field(
        ...,
        description='Auto-discovered reward/metric identifier, as returned by `GET /v1/metric-kinds`.',
    )
    weight: confloat(ge=0.0)
    deterministic: bool | None = False
    objective: bool | None = False
    # NOTE(#74): default must be the enum member (``Direction.max``), not the
    # bare string ``'max'``.  datamodel-codegen emits ``= 'max'`` for an enum
    # field with ``default: max`` in openapi.yaml, but a str default makes
    # Pydantic v2 raise PydanticSerializationUnexpectedValue on serialization
    # (and cascade misleading warnings through the discriminated unions that
    # embed MetricDefinition).  Keep this as ``Direction.max`` after any regen;
    # the wire value is identical ("max").
    direction: Direction | None = Direction.max
    backbone: str | None = Field(
        None,
        description='Provider/model/class backing the metric, for example `openai/gpt-4o`, `anthropic/claude-sonnet-4.5`, or `exact_match`.',
    )
    config: dict[str, Any] | None = None
    context_bindings: list[ContextBinding] | None = None


class VerifierSuiteCreate(BaseModel):
    name: str
    description: str | None = None
    aggregation: str | None = Field(
        'weighted_mean',
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`. Compliant servers must expose `weighted_mean`, which is the default value for this field.',
    )
    metrics: list[MetricDefinition] = Field(..., min_length=1)
    metadata: dict[str, Any] | None = None


class VerifierSuitePatch(BaseModel):
    name: str | None = None
    description: str | None = None
    aggregation: str | None = Field(
        None,
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`.',
    )
    metrics: list[MetricDefinition] | None = Field(None, min_length=1)
    metadata: dict[str, Any] | None = None


class VerifierSuite(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    aggregation: str | None = Field(
        None,
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`.',
    )
    metrics: list[MetricDefinition] = Field(..., min_length=1)
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class VerifierSuiteRef(BaseModel):
    binding_type: Literal['ref']
    verifier_id: UUID


class VerifierSuiteInline(BaseModel):
    binding_type: Literal['inline']
    name: str
    aggregation: str | None = Field(
        'weighted_mean',
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`. Compliant servers must expose `weighted_mean`, which is the default value for this field.',
    )
    metrics: list[MetricDefinition] = Field(..., min_length=1)


class EnvironmentSource(BaseModel):
    kind: EnvironmentSourceKind = Field(
        ...,
        description='Source registry for the canonical environment name, such as Hugging Face, a GitHub repo, Prime Intellect Environment Hub, or an inline definition.',
    )
    name: str = Field(
        ...,
        description='Canonical environment name for lookup and caching. When `inline_definition` is present, this should match `inline_definition.name`.',
    )
    version: str
    uri: AnyUrl | None = Field(
        None,
        description='Registry or repository URL; for `github_repo` sources this is the repository URL.',
    )
    external_id: str | None = Field(
        None,
        description='Provider-native identifier when the source registry exposes one.',
    )
    object_storage_layout: dict[str, Any] | None = None
    git_ref: str | None = Field(
        None, description='Git revision used when `kind` is `github_repo`.'
    )
    metadata: dict[str, Any] | None = None


class EnvironmentMembershipPatch(BaseModel):
    overrides: dict[str, Any] | None = None


class EnvironmentRef(BaseModel):
    environment_id: UUID


class RankingPolicy(BaseModel):
    primary_metric: str
    tie_breakers: list[str] | None = None
    aggregation: str | None = Field(
        'weighted_mean',
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`. Compliant servers must expose `weighted_mean`, which is the default value for this field.',
    )


class RankingPolicyPatch(BaseModel):
    primary_metric: str | None = None
    tie_breakers: list[str] | None = None
    aggregation: str | None = Field(
        'weighted_mean',
        description='Auto-discovered aggregation identifier, as returned by `GET /v1/aggregations`. Compliant servers must expose `weighted_mean`, which is the default value for this field.',
    )


class LeaderboardPatch(BaseModel):
    name: str | None = None
    description: str | None = None
    visibility: LeaderboardVisibility | None = None
    ranking: RankingPolicyPatch | None = None
    metadata: dict[str, Any] | None = None


class ReuseScope(StrEnum):
    leaderboard_only = 'leaderboard_only'
    organization = 'organization'
    global_ = 'global'


class ReusePolicy(BaseModel):
    enabled: bool | None = True
    # NOTE(#74): default must be the enum member (``ReuseScope.global_``), not
    # the bare string ``'global'`` — same Pydantic v2 serializer-warning issue
    # as MetricDefinition.direction above.  Keep after regen; wire value is
    # identical ("global").
    reuse_scope: ReuseScope | None = ReuseScope.global_
    key_fields: list[str] | None = [
        'model_version',
        'environment_version',
        'mode',
        'temperature',
        'max_tokens',
    ]
    allow_partial_cache: bool | None = True


class GeneratorRunConfig(BaseModel):
    generator_overrides: dict[str, Any] | None = None


class AgentRunConfig(BaseModel):
    agent_overrides: dict[str, Any] | None = None
    capture_trajectory: bool | None = True


class CacheHit(BaseModel):
    model_name: str
    model_version: str
    environment_name: str
    environment_version: str
    status: CacheStatus
    prior_run_id: UUID | None = None


class RunStatus(StrEnum):
    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelled = 'cancelled'


class MetricResult(BaseModel):
    name: str
    value: float
    direction: Direction
    weight: float | None = None
    metadata: dict[str, Any] | None = None


class TrajectorySummary(BaseModel):
    total_steps: conint(ge=0) | None = None
    tool_calls: conint(ge=0) | None = None
    failures: conint(ge=0) | None = None


class AggregateMetric(BaseModel):
    name: str
    value: float
    aggregation: str = Field(
        ..., description='Aggregation identifier used for the returned aggregate value.'
    )


class LeaderboardEntry(BaseModel):
    rank: conint(ge=1)
    model_id: UUID
    model_version: str
    environment_id: UUID
    environment_version: str
    score: float
    environment_breakdown: dict[str, float] | None = Field(
        None,
        description='Optional per-entry subscore breakdown; keys are implementation-defined labels, not environment identifiers.',
    )
    last_run_id: UUID | None = None

class ModelDefinitionListResponse(BaseModel):
    items: list[ModelDefinition]
    next_cursor: str | None = None


class VerifierSuiteListResponse(BaseModel):
    items: list[VerifierSuite]
    next_cursor: str | None = None


class LeaderboardEntryListResponse(BaseModel):
    items: list[LeaderboardEntry]
    next_cursor: str | None = None

class DiscoveryIdentifier(BaseModel):
    id: str
    display_name: str | None = None
    description: str | None = None
    scopes: list[str] | None = None
    metadata: dict[str, Any] | None = None


class DiscoveryIdentifierListResponse(BaseModel):
    items: list[DiscoveryIdentifier]


class ErrorDetail(BaseModel):
    code: str
    message: str
    details: dict[str, Any] | None = None


class VerifierSuiteBinding(RootModel[VerifierSuiteRef | VerifierSuiteInline]):
    root: VerifierSuiteRef | VerifierSuiteInline = Field(
        ..., discriminator='binding_type'
    )


class InlineEnvironmentDefinition(BaseModel):
    name: str
    version: str
    description: str | None = None
    dataset: DatasetBinding
    verifier: VerifierSuiteBinding
    runtime: EnvironmentRuntimePolicy
    sandbox: SandboxPolicy | None = None
    reset_policy: ResetPolicy | None = None
    metadata: dict[str, Any] | None = None


class EnvironmentCreate(BaseModel):
    source: EnvironmentSource
    inline_definition: InlineEnvironmentDefinition | None = None
    metadata: dict[str, Any] | None = None


class EnvironmentPatch(BaseModel):
    source: EnvironmentSource | None = None
    inline_definition: InlineEnvironmentDefinition | None = None
    metadata: dict[str, Any] | None = None


class Environment(BaseModel):
    id: UUID
    source: EnvironmentSource
    inline_definition: InlineEnvironmentDefinition | None = None
    # WS3: resolved pinned identity — populated on create/update when the
    # backend supports it (git-backed sources).  Null for inline environments.
    commit_sha: str | None = None
    content_hash: str | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class EnvironmentInlineMembership(BaseModel):
    inline_definition: InlineEnvironmentDefinition


class EnvironmentMembership(BaseModel):
    environment_id: UUID
    environment: Environment
    overrides: dict[str, Any] | None = None
    created_at: AwareDatetime


class Leaderboard(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    visibility: LeaderboardVisibility
    ranking: RankingPolicy
    model_catalog: ModelCatalog | None = None
    environments: list[EnvironmentMembership] | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DirectRunPair(BaseModel):
    model: ModelDefinitionCreate
    environment: EnvironmentRef | EnvironmentInlineMembership


class SubjectResult(BaseModel):
    model: ModelDefinition
    environment: Environment
    metrics: list[MetricResult] = Field(..., min_length=1)
    cache_status: CacheStatus
    trajectory_summary: TrajectorySummary | None = None
    run_fingerprint: str | None = Field(
        None,
        description='Deterministic cache key computed from the active `ReusePolicy.key_fields`; by default this includes model_version, environment_version, mode, temperature, and max_tokens.',
    )


class RunResult(BaseModel):
    run_id: UUID
    mode: RunMode
    subjects: list[SubjectResult] = Field(..., min_length=1)
    aggregates: list[AggregateMetric] | None = None


class EnvironmentMembershipListResponse(BaseModel):
    items: list[EnvironmentMembership]
    next_cursor: str | None = None


class EnvironmentListResponse(BaseModel):
    items: list[Environment]
    next_cursor: str | None = None


class EnvironmentVersion(BaseModel):
    """A single version descriptor for an environment (WS3: environment versioning)."""

    version: str
    commit_sha: str | None = None
    content_hash: str | None = None
    git_ref: str | None = None
    created_at: AwareDatetime | None = None


class EnvironmentVersionListResponse(BaseModel):
    items: list[EnvironmentVersion]
    next_cursor: str | None = None


class LeaderboardListResponse(BaseModel):
    items: list[Leaderboard]
    next_cursor: str | None = None


class Error(BaseModel):
    error: ErrorDetail


class EnvironmentMembershipCreate(BaseModel):
    environment: EnvironmentRef | EnvironmentInlineMembership
    overrides: dict[str, Any] | None = None


class LeaderboardBootstrap(BaseModel):
    model_catalog: ModelCatalogReplace | None = None
    environments: list[EnvironmentMembershipCreate] | None = Field(None, min_length=1)


class LeaderboardCreate(BaseModel):
    name: str
    description: str | None = None
    visibility: LeaderboardVisibility | None = None
    ranking: RankingPolicy | None = None
    bootstrap: LeaderboardBootstrap | None = None
    metadata: dict[str, Any] | None = None


class RunSelection1(BaseModel):
    leaderboard_id: UUID
    model_ids: list[UUID] | None = Field(None, min_length=1)
    environment_ids: list[UUID] | None = Field(None, min_length=1)
    direct_pairs: list[DirectRunPair] | None = Field(None, min_length=1)
    publish_to_public_leaderboard: bool | None = False


class RunSelection2(BaseModel):
    leaderboard_id: UUID | None = None
    model_ids: list[UUID] | None = Field(None, min_length=1)
    environment_ids: list[UUID] | None = Field(None, min_length=1)
    direct_pairs: list[DirectRunPair] = Field(..., min_length=1)
    publish_to_public_leaderboard: bool | None = False


class RunSelection(RootModel[RunSelection1 | RunSelection2]):
    root: RunSelection1 | RunSelection2


class GeneratorRunCreate(BaseModel):
    mode: Literal['generator']
    selection: RunSelection
    reuse_policy: ReusePolicy | None = None
    execution: GeneratorRunConfig | None = None
    labels: dict[str, str] | None = None
    idempotency_key: str | None = None


class AgentRunCreate(BaseModel):
    mode: Literal['agent']
    selection: RunSelection
    reuse_policy: ReusePolicy | None = None
    execution: AgentRunConfig | None = None
    labels: dict[str, str] | None = None
    idempotency_key: str | None = None


class Run(BaseModel):
    id: UUID
    mode: RunMode
    selection: RunSelection
    status: RunStatus
    cache_status: CacheStatus
    cache_hits: list[CacheHit] | None = None
    labels: dict[str, str] | None = None
    created_at: AwareDatetime
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    error: ErrorDetail | None = None


class RunListResponse(BaseModel):
    items: list[Run]
    next_cursor: str | None = None


class RunCreate(RootModel[GeneratorRunCreate | AgentRunCreate]):
    root: GeneratorRunCreate | AgentRunCreate = Field(..., discriminator='mode')
